import schoolImage from '../../assets/images/school-portfolio.png'

export const schoolPortfolio = [
  {
    lettersArray: [
      'S',
      'c',
      'h',
      'o',
      'o',
      'l',
      ' ',
      'M',
      'a',
      'n',
      'a',
      'g',
      'e',
      'm',
      'e',
      'n',
      't',
      ' ',
      'S',
      'y',
      's',
      't',
      'e',
      'm',
    ],
    techArray: [
      'ReactJS',
      'TailwindCSS',
      'NextJS',
      'Redux Toolkit Query',
      'MongoDB',
    ],
    featuresArray: [
      'CRUD (Create, Read, Update, Delete)',
      'Manage school data',
      'Dashboard',
      'Responsive Layout (Desktop and Mobile)',
      'Login Authentication (Students, Teachers, Admin)',
      'Chat system (Coming soon)',
    ],
    demoLink: '',
    codeLink: '',
    portfolioImage: { schoolImage },
  },
  {
    lettersArray: [
      'W',
      'e',
      'a',
      't',
      'h',
      'e',
      'r',
      ' ',
      'A',
      'p',
      'p',
      'l',
      'i',
      'c',
      'a',
      't',
      'i',
      'o',
      'n',
    ],
    techArray: ['HTML', 'CSS', 'Vanilla JS', 'Openweathermap API'],
    featuresArray: [
      'Real time weather',
      '7 days weather prediction (coming soon)',
      '24 hour weather prediction (coming soon',
      'Responsive Layout (Desktop and Mobile)',
    ],
    demoLink: '',
    codeLink: '',
    portfolioImage: { schoolImage },
  },
]
