import schoolImage from '../../assets/images/school-portfolio.png'
import weatherImage from '../../assets/images/weather-app.png'

export const schoolPortfolio = {
  letterSchool: [
    'S',
    'c',
    'h',
    'o',
    'o',
    'l',
    ' ',
    'M',
    'a',
    'n',
    'a',
    'g',
    'e',
    'm',
    'e',
    'n',
    't',
    ' ',
    'S',
    'y',
    's',
    't',
    'e',
    'm',
  ],
  techSchool: [
    'ReactJS',
    'TailwindCSS',
    'NextJS',
    'Redux Toolkit Query',
    'MongoDB',
  ],
  featuresSchool: [
    'CRUD (Create, Read, Update, Delete)',
    'Manage school data',
    'Dashboard',
    'Responsive Layout (Desktop and Mobile)',
    'Login Authentication (Students, Teachers, Admin)',
    'Chat system (Coming soon)',
  ],
  demoSchool: '',
  codeSchool: '',
  imageSchool: schoolImage,
}

export const weatherPortfolio = {
  lettersWeather: [
    'W',
    'e',
    'a',
    't',
    'h',
    'e',
    'r',
    ' ',
    'A',
    'p',
    'p',
    'l',
    'i',
    'c',
    'a',
    't',
    'i',
    'o',
    'n',
  ],
  techWeather: ['HTML', 'CSS', 'Vanilla JS', 'Openweathermap API'],
  featuresWeather: [
    'Real time weather',
    '7 days weather prediction (coming soon)',
    '24 hour weather prediction (coming soon',
    'Responsive Layout (Desktop and Mobile)',
  ],
  demoWeather: 'https://riandev25.github.io/js-weather-app/dist/',
  codeWeather: 'https://github.io/riandev25/js-weather-app',
  imageWeather: weatherImage,
}
